version: '3.4'
services:
  landing:
        image: nginx
        container_name: chq_landing
        networks:
          - web
        volumes:
          - ./out:/usr/share/nginx/html
        labels:
          - traefik.http.routers.landing.rule=Host(`codershq.ae`)
          - traefik.http.routers.landing.tls=true
          - traefik.http.routers.landing.tls.certresolver=lets-encrypt
          - traefik.port=80
        env_file:
          - ./.envs/.local
